name: postman-push
on: [push] 

jobs:
  build1:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
          nodes: [16,18]
  
    steps:
  
    - name: Check out Git repository
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.nodes}}

    - name: Install newman
      run: npm install -g newman

    - name: Run the API and Postman's tests
      run: newman run SQA-Exam/Books.postman_collection.json -e test.postman_environment.json 
